---
apiVersion: v1
kind: Namespace
metadata:
  name: objectstorage-provisioner-ns
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-minio
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-minio