apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-provisioner
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-minio
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-minio
type: Opaque
stringData:
  MINIO_HOST: "http://minio:9000"
  MINIO_ACCESS_KEY: "minio"
  MINIO_SECRET_KEY: "minio123"
  V: "3"
